name: Firebase Functions deploy workflow

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - name: Install node modules
        run: npm ci
        working-directory: functions
        env:
            CI: true

      - name: Deploy Functions to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    