name: Firebase Hosting deploy workflow

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://arkid-firebase-experiments.web.app/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20

      - name: Deploy Hosting to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    