name: Firebase deploy workflow

on:
  workflow_dispatch:

# permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
